import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Tutorial',
      items: [{type: 'autogenerated', dirName: 'tutorial-basics'}],
    },
    {
      type: 'category',
      label: 'Tutorial Extras',
      items: [{type: 'autogenerated', dirName: 'tutorial-extras'}],
    },
    {
      type: 'category',
      label: 'ROS 2 for Humanoid Robotics',
      items: [
        'ros2-humanoid-nervous-system/chapter-1-ros2-fundamentals',
        'ros2-humanoid-nervous-system/chapter-2-python-agents-rclpy',
        'ros2-humanoid-nervous-system/chapter-3-urdf-humanoid-description'
      ],
    },
    {
      type: 'category',
      label: 'AI-Robot Brain (NVIDIA Isaac™)',
      items: [
        'ai-robot-brain-nvidia-isaac/chapter-1-isaac-sim',
        'ai-robot-brain-nvidia-isaac/chapter-2-isaac-ros',
        'ai-robot-brain-nvidia-isaac/chapter-3-nav2-humanoid-navigation'
      ],
    },
    {
      type: 'category',
      label: 'Digital Twin (Gazebo & Unity)',
      items: [
        'digital-twin-gazebo-unity/chapter-1-gazebo-physics-simulation',
        'digital-twin-gazebo-unity/chapter-2-unity-digital-twins',
        'digital-twin-gazebo-unity/chapter-3-sensor-simulation'
      ],
    },
    {
      type: 'category',
      label: 'Vision-Language-Action (VLA)',
      items: [
        'vla-integration/chapter-1-voice-to-action',
        'vla-integration/chapter-2-cognitive-planning',
        'vla-integration/chapter-3-vla-capstone'
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
